baseURL = 'https://hugo-test-gamma-eight.vercel.app/'
languageCode = 'en-us'
title = 'Yoko Hugo Test Site'
theme = 'ananke' 

[params]
  custom_css = ['css/custom.css']
  background = "/images/hero.jpg"